code --install-extension adamsome.vscode-theme-gruvbox-minor
code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.project-manager
code --install-extension anseki.vscode-color
code --install-extension ban.spellright
code --install-extension be5invis.vscode-icontheme-nomo-dark
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.toggle-excluded-files
code --install-extension ephoton.indent-switcher
code --install-extension formulahendry.code-runner
code --install-extension gebilaoxiong.vscode-flatland-icon-theme
code --install-extension GracefulPotato.gruvbox-ish
code --install-extension Gruntfuggly.todo-tree
code --install-extension gsakkas.gruvbox-mix
code --install-extension hashicorp.terraform
code --install-extension James-Yu.latex-workshop
code --install-extension jdinhlife.gruvbox
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension kangping.protobuf
code --install-extension Kelvin.vscode-sshfs
code --install-extension konradkeska.subliminal-next
code --install-extension lkytal.FlatUI
code --install-extension michelemelluso.gitignore
code --install-extension Miglisoft.dark-pastel-theme
code --install-extension ms-vscode.sublime-keybindings
code --install-extension npxms.hide-gitignored
code --install-extension ow.vscode-subword-navigation
code --install-extension patbenatar.advanced-new-file
code --install-extension piotrpalarz.vscode-gitignore-generator
code --install-extension rafamel.subtle-brackets
code --install-extension redhat.java
code --install-extension ryu1kn.partial-diff
code --install-extension sainnhe.gruvbox-material
code --install-extension sohibe.java-generate-setters-getters
code --install-extension spikespaz.vscode-smoothtype
code --install-extension techer.open-in-browser
code --install-extension tomoki1207.pdf
code --install-extension tomsaunders.vscode-workspace-explorer
code --install-extension usernamehw.errorlens
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-ext.sync-rsync
code --install-extension wheredoesyourmindgo.gruvbox-concoctis
code --install-extension Yummygum.city-lights-icon-vsc
code --install-extension yzhang.markdown-all-in-one
