#!/bin/bash

repo="init /path/to/directory"
status="status"
add="add 'filename'"
reset="reset 'filename'"
untrack="git rm --cached 'filename'"
commit="commit -m 'Description'"
log="log"
remote="remote add 'label' 'repo url'"
push="push 'label' 'repo branch'"
pull="pull 'label' 'repo branch'"
HEAD="diff HEAD"
check="checkout -- 'filename'"
remoter="remote rm 'label'"
remotes="remote -v"
res="reset --hard HEAD~n"
branch1="checkout -b 'new branch'"
branch2="checkout 'branch name'"


printf "\n$repo		   create local repo\n\n"
printf "$remote  	   connect to a github repo (for no login use git+ssh://git@github.com/username/reponame.git)\n"
printf "$remoter  		   remove connection to github repo\n"
printf "$remotes  			   show current connections\n\n"
printf "$status				   current directory status\n"
printf "$res		   discard the previous n commits\n\n"
printf "$add			   add a file to the staging area\n"
printf "$reset		   remove a file from the staging area (* for all)\n"
printf "$untrack	   untrack a file\n"
printf "$commit		   add staged files to local repo\n\n"
printf "$log				   show commit history\n"
printf "$HEAD			   see differences since last commit\n"
printf "$check 		   restore to last commit of the file\n\n"
printf "$branch1 	   create new branch\n"
printf "$branch2 		   switch to a different branch\n\n"
printf "$pull	   pull current github repo to local repo\n"
printf "$push	   push local changes to github repo\n"
printf "				note: use -u to remember parameters\n 				and next time just write git push\n"
