#!/bin/bash

repo="init /path/to/directory"
status="status"
add="add 'filename'"
reset="reset file.txt"
commit="commit -m 'Description'"
log="log"
remote="remote add 'label' 'repo url'"
push="push 'label' 'repo branch'"
pull="pull 'label' 'repo branch'"
HEAD="diff HEAD"
check="checkout -- 'filename'"
remoter="remote rm 'label'"
res="reset --hard"


printf "\n$repo		   create local repo\n\n"
printf "$remote  	   connect to a github repo\n"
printf "$remoter  		   remove connection to github repo\n\n"
printf "$status				   current directory status\n"
printf "$res			   restore everything to the previous commit\n\n"
printf "$add			   add a file to the staging area\n"
printf "$reset			   remove a file from the staging area\n"
printf "$commit		   add staged files to local repo\n\n"
printf "$log				   show commit history\n"
printf "$HEAD			   see differences since last commit\n"
printf "$check 		   restore to last commit of the file\n\n"
printf "$pull	   pull current github repo to local repo\n"
printf "$push	   push local changes to github repo\n"
printf "				note: use -u to remember parameters\n 				and next time just write git push\n"
